### ISSUE TITLE
BCD table in "text-decoration-style" page is broken when notes are expanded

### ISSUE THREAD

**Issue by wbamberg** [mdn/kuma#6968]
Take the BCD table at https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style#Browser_compatibility:

*******
<img width="1033" alt="Screen Shot 2020-04-29 at 10 51 09 AM" src="https://user-images.githubusercontent.com/432915/80629211-5ee9b480-8a07-11ea-838e-f465e9bcfe3e.png">

*******

It contains two rows, and the first row has some notes that we can see by clicking a disclosure arrow.

Click one of the note disclosure arrows in the top row:

*******
<img width="1033" alt="Screen Shot 2020-04-29 at 10 51 25 AM" src="https://user-images.githubusercontent.com/432915/80629270-7a54bf80-8a07-11ea-9703-688380953a73.png">

*******

Most of the second row is pushed out of the box and the names of the rows disappear.

I suspect this is because the name of the first row `text-decoration-style` wraps, so that row is taller than normal.

**Comment by peterbe** [comment]
The BCD table has been forked in Yari (by a contributor no less!) Whatever improvements we do to the KS version, we should port to the new React version.

However, it actually seems to work fine there:
<img width="931" alt="Screen Shot 2020-04-29 at 2 16 48 PM" src="https://user-images.githubusercontent.com/26739/80631755-3a500580-8a24-11ea-9352-1ec08a009f56.png">

**Comment by Elchi3** [comment]
Duplicate of https://github.com/mdn/kuma/issues/6845 which I've asked to prioritize.

**Comment by atopal** [comment]
Closing, as it's a duplicate.

**Comment by wbamberg** [comment]
This is only partly fixed by https://github.com/mdn/kuma/issues/6845. The row name doesn't disappear any more, but the row after it is still cut off:

<img width="1046" alt="Screen Shot 2020-05-13 at 9 29 24 AM" src="https://user-images.githubusercontent.com/432915/81839220-1a2c4600-94fc-11ea-8e7b-c488eb8847ad.png">

**Comment by atopal** [comment]
Was this fixed? I can't reproduce this anymore.

**Comment by danielzgtg** [comment]
This bug still affects me.

![image](https://user-images.githubusercontent.com/25646384/83793422-8406be00-a66a-11ea-9656-84db17e076b4.png)

**Comment by schalkneethling** [comment]
Thank you @danielzgtg. It is on my todo list. I will let you know once this has landed on production.
